config/routes.rb
Accounting::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "pages#landing"
  get "home", to: "pages#home", as: "home", as: :user_root
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"

  resources :subscribers, only: :create
  devise_for :users
  resources :subscriptions do
    resources :payments
  end

  resources :firms do
    collection do
      post 'switch'
    end
    resources :memberships
    resources :fiscal_years, only: [:new, :create]
    resources :cash_flows, only: [:show]
    resources :balance_sheets, only: [:show]
    resources :income_statements, only: [:show]
    resources :spendings
    resources :payable_payments
    resources :receivable_payments
    resources :assets do
      collection do
        post 'refresh'
      end
    end
    resources :expenses
    resources :revenues
    resources :other_revenues
    resources :discards
    resources :funds
    resources :loans
    resources :expendables
    resources :merchandises
    resources :works
    resources :materials
    resources :products
    resources :assemblies
  end

  resources :assemblies do
    resources :processings, only: [:index]
  end

  resources :fiscal_years do
    collection do
      post 'closing'
    end
    resources :cash_flows, only: [:show]
    resources :balance_sheets, only: [:show]
    resources :income_statements, only: [:show]
  end

  namespace :admin do
    root "base#index"
    get "out_email", to: "base#out_email"
    post "send_outbound", to: "base#send_outbound"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
    resources :plans
    resources :messages, only: [:index, :new, :create]
    resources :bookings      
  end

end

app/controllers/merchandises_controller.rb
class MerchandisesController < ApplicationController
  before_action :set_firm
  before_action :set_merchandise, only: [:show, :edit, :update]

  def index
    @merchandises = @firm.merchandises.all
    # @merch_groups = @firm.merchandises.all.group_by { |item| item.merch_name  }
    @revenues = @firm.revenues.by_type('Merchandise')
  end

  # def new
  #   @merch = @firm.merchandises.build
  # end

  # def create
  #   @merch = @firm.merchandises.build(merchandise_params)

  #   respond_to do |format|
  #     if @merch.save
  #       format.html { redirect_to firm_merchandises_path(@firm), notice: 'Jenis produk berhasil dicatat' }
  #       format.json { render :show, status: :created, location: @merch }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @merch.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def edit
  end

  def update
    respond_to do |format|
      if @merch.update(merchandise_params)
        format.html { redirect_to firm_merchandises_path(@firm), notice: 'Jenis produk berhasil dikoreksi' }
        format.json { render :show, status: :created, location: @merch }
      else
        format.html { render :new }
        format.json { render json: @merch.errors, status: :unprocessable_entity }
      end
    end
  end  

  # def destroy
  #   @merchandise.destroy
  #   respond_to do |format|
  #     format.html { redirect_to merchandises_url, notice: 'Merchandise was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchandise
      @merchandise = @firm.merchandises.find(params[:id])
    end

    def merchandise_params
      params.require(:merchandise).permit(
        :item_name, :quantity, :measurement, :cost
      )
    end
end

app/helpers/merchandises_helper.rb
module MerchandisesHelper

	def cost_accumulated(array)
		array.map(&:cost).compact.sum
	end

	def show_cost_per_unit(merch)
		value = idr_money(merch.cost_per_unit)
		measured = merch.measurement
		return "#{value} per #{measured}"
	end

	def count_payables
		arr.map do |x|
			arr_1 = x[:spending_id]
			arr_1.each do |merch|
				Spending.find_by_id(merch)
			end
		end
	end

end

app/views/merchandises/_form.html.erb
<%= bootstrap_form_for([@firm, @merch], layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-9") do |f| %>

  <%= render 'shared/error_messages', object: @merch %>

  <div class="container">
    <div class="well row">

      <div class="col-xs-12 col-sm-12" data-toggle="tooltip" 
           title="<%= name_tip_text('produk') %>">
        <%= f.text_field :merch_name, label: "Nama Produk" %>
      </div>
      <div class="col-xs-12 col-sm-12" data-toggle="tooltip" 
         title="<%= measurement_tip_text('produk') %>">
        <%= f.text_field :measurement, label: "Satuan Ukuran" %>
      </div>
      <div class="col-xs-12 col-sm-12">
        <%= f.text_field :price, label: "Harga Jual", data: {autonumeric: {aSign: 'Rp ', aSep: '.', aDec: ',', mDec: 0}} %>
      </div>      
    </div>

    <div class="actions">
      <%= f.submit "Simpan", class: "btn btn-primary" %>
    </div>    
  </div>

<% end %>

app/views/merchandises/_index.html.erb
<% title("Daftar Stok Dagang") %>
<h1 class="text-center">Daftar Stok Dagang</h1> 
<hr></hr>   
<% @merch_groups.each_with_index do |(name, items), index| %>

<div class="container" id="<%= index %>">
  <div class="row user-menu-container square">

    <div class="col-md-7 user-details">

      <div class="row">
        <div class="col-md-6 no-pad coralbg white">
          <div class="user-pad">
            <h3><%= name %></h3>
            <h5 class="white">
              <i class="fa fa-check-circle-o"></i> 
              <%= items.count %> Catatan pembelian
            </h5>
            <h5 class="white">
              <i class="fa fa-warning"></i>
            </h5><br>
          </div>
        </div>
        <div class="col-md-6 no-pad">
          <div class="col-md-12 no-pad text-center">
            <h3>NILAI PEMBELIAN</h3>
            <h4 class="cost"><%= accumulator(items, 'cost', 'money') %></h4>
          </div>
          <div class="col-md-12 no-pad text-center">
              <h3>TOTAL PEMBELIAN</h3>
              <h4>
                <%= accumulator(items, 'quantity', 'decimal') %> 
                <%= items.first.measurement %>
              </h4>
          </div>          
        </div>
      </div>
      <div class="row overview">
          <div class="col-md-2 user-pad text-center">
              <h3>STOK SEKARANG</h3>
              <h4 class="remaining">
                <%= unit_remaining(items, 'quantity', 'quantity_sold', 'decimal') %>
              </h4>
          </div>
          <div class="col-md-5 user-pad text-center">
              <h3>BIAYA/UNIT</h3>
              <h4 class="unit_cost"><%= averager(items, 'cost_per_unit') %></h4>
          </div>
          <div class="col-md-5 user-pad text-center">
              <h3>NILAI TERJUAL</h3>
              <h4 class="sold">
                <%= accumulator(items, 'cost_sold', 'money') %> 
              </h4>
          </div>
      </div>
    </div>

    <div class="col-md-1 user-menu-btns">
        <div class="btn-group-vertical square" id="responsive">
            <a href="#tab_<%= index %>_1" class="btn btn-block btn-default active action" data-toggle="tab">
              <i class="fa fa-shopping-cart fa-3x"></i>
            </a>
            <a href="#tab_<%= index %>_2" class="btn btn-default" data-toggle="tab">
              <i class="fa fa-money fa-3x"></i>
            </a>            
            <a href="#tab_<%= index %>_3" class="btn btn-default" data-toggle="tab">
              OPSI
            </a>            
        </div>
    </div>

    <div class="col-md-4 user-menu user-pad">
        <div class="user-menu-content active"  id="tab_<%= index %>_1">
          <h3 class="text-center">Riwayat Pembelian</h3>
          <ul class="user-menu-list">

            <% items.each do |item| %>
            <li class="row">
              <div class="col-sm-12" style="padding-left: 5px;">
                <small class="quantity"><i class="fa fa-clock-o"></i> 
                  <%= item.date_purchased %> | beli <%= (item.quantity) %>
                  <%= (item.measurement) %> | <%= has_payable?(item) %>
                </small>
              <div class="col-sm-12" style="padding-left: 5px;">
                <h5 class="cost coral">
                  <%= idr_money(item.cost) %>
                  (<%= show_cost_per_unit(item) %>) 
                </h5>
              </div>
              <div class="col-sm-12">
                <%= link_to "Koreksi", edit_firm_spending_path(@firm, item.spending, type: 'Merchandise') %>
              </div>              
            </li>
            <% end %>

          </ul>
        </div>

        <div class="user-menu-content"  id="tab_<%= index %>_2">
          <h3 class="text-center">Riwayat Penjualan</h3>
          <ul class="user-menu-list">

            <% @revenues.each do |revenue| %>
              <li class="row">
                <div class="col-sm-12" style="padding-left: 5px;">
                  <small><i class="fa fa-clock-o"></i> 
                    <%= revenue.date_of_revenue %> | jual <%= (revenue.quantity) %> <%= (revenue.item.measurement) %> | (<%= status_of_earning(revenue) %>)
                  </small>
                </div>
                <div class="col-sm-12">
                  <p class="coral">dengan total <%= idr_money(revenue.total_earned) %> 
                  </p>
                </div>
              </li>
            <% end %>

          </ul>
        </div>

        <div class="user-menu-content"  id="tab_<%= index %>_3">
          <h3 class="text-center">Opsi Tindakan</h3>
          <ul class="user-menu-list">
            <li>
              <%= link_to new_firm_spending_path(@firm, type: 'Merchandise', name: name, measure: items.first.measurement), class: "btn btn-labeled btn-lg btn-warning" do %>
                <span class="btn-label"><i class="fa fa-shopping-cart"></i></span>Catat Penambahan
              <% end %>                    
            </li>
          </ul>
        </div>        
    </div>


  </div>
</div>

<% end %>
<%= link_to "Kembali Ke Home", user_root_path %>  

app/views/merchandises/edit.html.erb
<h1>Koreksi Jenis Produk</h1>

<%= render 'form' %>

<%= link_to 'Kembali ke Home', user_root_path %>

app/views/merchandises/index.html.erb
<% title("Daftar Stok Dagang") %>
<h1 class="text-center">Daftar Stok Dagang</h1> 
<hr></hr>   
<% @merchandises.each do |merch| %>

<div class="container" id="<%= merch.id %>">
  <div class="row user-menu-container square">

    <div class="col-md-7 user-details">

      <div class="row">
        <div class="col-md-6 no-pad coralbg white">
          <div class="user-pad">
            <h3><%= merch.item_name %></h3>
            <h5 class="white">
              <i class="fa fa-check-circle-o"></i> 
              <%= merch.related_spendings.count %> Catatan pembelian
              <%= merch.related_earnings.count %> Catatan penjualan
            </h5>
            <h5 class="white">
              <i class="fa fa-warning"></i>
            </h5><br>
          </div>
        </div>
        <div class="col-md-6 no-pad">
          <div class="col-md-12 no-pad text-center">
            <h3>NILAI PEMBELIAN</h3>
            <h4 class="cost"><%= idr_money(merch.cost) %></h4>
          </div>
          <div class="col-md-12 no-pad text-center">
              <h3>BIAYA PER SATUAN</h3>
              <h4 class="unit_cost">
                <%= idr_money(merch.cost_per_unit) %>
              </h4>
          </div>          
        </div>
      </div>
      <div class="row overview">
          <div class="col-md-4 user-pad text-center">
              <h3>JUMLAH STOK</h3>
              <h4 class="remaining">
                <%= merch.quantity_remaining %>
              </h4>
          </div>
          <div class="col-md-4 user-pad text-center">
              <h3>NILAI STOK (Rp)</h3>
              <h4><%= idr_no_symbol(merch.cost_remaining) %></h4>
          </div>
          <div class="col-md-4 user-pad text-center">
              <h3>TERJUAL (Rp)</h3>
              <h4 class="sold">
                <%= idr_no_symbol(merch.cost_used) %>
              </h4>
          </div>
      </div>
    </div>

    <div class="col-md-1 user-menu-btns">
        <div class="btn-group-vertical square" id="responsive">
            <a href="#tab_<%= merch.id %>_1" class="btn btn-block btn-default active action" data-toggle="tab">
              <i class="fa fa-shopping-cart fa-3x"></i>
            </a>
            <a href="#tab_<%= merch.id %>_2" class="btn btn-default" data-toggle="tab">
              <i class="fa fa-money fa-3x"></i>
            </a>            
            <a href="#tab_<%= merch.id %>_3" class="btn btn-default" data-toggle="tab">
              OPSI
            </a>            
        </div>
    </div>

    <div class="col-md-4 user-menu user-pad">
        <div class="user-menu-content active"  id="tab_<%= merch.id %>_1">
          <h3 class="text-center">Riwayat Pembelian</h3>
          <ul class="user-menu-list">

            <% merch.related_spendings.each do |item| %>
            <li class="row">
              <div class="col-sm-12" style="padding-left: 5px;">
                <small class="quantity"><i class="fa fa-clock-o"></i> 
                  <%= item.date_of_spending %> | beli <%= (item.quantity) %>
                  <%= (item.measurement) %> | <%= is_payable?(item) %>
                </small>
              <div class="col-sm-12" style="padding-left: 5px;">
                <h5 class="cost coral">
                  <%= idr_money(item.total_spent) %>
                </h5>
              </div>
              <div class="col-sm-12">
                <%= link_to "Koreksi", edit_firm_spending_path(@firm, item, type: 'Merchandise') %>
              </div>              
            </li>
            <% end %>

          </ul>
        </div>

        <div class="user-menu-content"  id="tab_<%= merch.id %>_2">
          <h3 class="text-center">Riwayat Penjualan</h3>
          <ul class="user-menu-list">

            <% merch.related_earnings.each do |revenue| %>
              <li class="row">
                <div class="col-sm-12" style="padding-left: 5px;">
                  <small><i class="fa fa-clock-o"></i> 
                    <%= revenue.date_of_revenue %> | jual <%= (revenue.quantity) %> <%= (revenue.item.measurement) %> | (<%= status_of_earning(revenue) %>)
                  </small>
                </div>
                <div class="col-sm-12">
                  <p class="coral">dengan total <%= idr_money(revenue.total_earned) %> 
                  </p>
                </div>
              </li>
            <% end %>

          </ul>
        </div>

        <div class="user-menu-content"  id="tab_<%= merch.id %>_3">
          <h3 class="text-center">Opsi Tindakan</h3>
          <ul class="user-menu-list">
            <li>
              <%= link_to new_firm_spending_path(@firm, type: 'Merchandise', name: merch.item_name, measure: merch.measurement), class: "btn btn-labeled btn-lg btn-warning" do %>
                <span class="btn-label"><i class="fa fa-shopping-cart"></i></span>Catat Penambahan
              <% end %>                    
            </li>
          </ul>
        </div>        
    </div>


  </div>
</div>

<% end %>
<%= link_to "Kembali Ke Home", user_root_path %>  

app/views/merchandises/new.html.erb
<h1>Catat Jenis Produk</h1>

<%= render 'form' %>

<%= link_to 'Kembali ke Home', user_root_path %>