config/routes.rb
Accounting::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "pages#landing"
  get "home", to: "pages#home", as: "home", as: :user_root
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"

  resources :subscribers, only: :create
  devise_for :users
  resources :subscriptions do
    resources :payments
  end

  resources :firms do
    collection do
      post 'switch'
    end
    resources :memberships
    resources :fiscal_years, only: [:new, :create]
    resources :cash_flows, only: [:show]
    resources :balance_sheets, only: [:show]
    resources :income_statements, only: [:show]
    resources :spendings
    resources :payable_payments
    resources :receivable_payments
    resources :assets do
      collection do
        post 'refresh'
      end
    end
    resources :expenses
    resources :revenues
    resources :other_revenues
    resources :discards
    resources :funds
    resources :loans
    resources :expendables
    resources :merchandises
    resources :works
    resources :materials
    resources :products
    resources :assemblies
  end

  resources :assemblies do
    resources :processings, only: [:index]
  end

  resources :fiscal_years do
    collection do
      post 'closing'
    end
    resources :cash_flows, only: [:show]
    resources :balance_sheets, only: [:show]
    resources :income_statements, only: [:show]
  end

  namespace :admin do
    root "base#index"
    get "out_email", to: "base#out_email"
    post "send_outbound", to: "base#send_outbound"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
    resources :plans
    resources :messages, only: [:index, :new, :create]
    resources :bookings      
  end

end

app/models/firms/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :user, foreign_key: 'user_id'
	belongs_to :firm, foreign_key: 'firm_id'
	validates_associated :user
	validates_associated :firm

	scope :by_firm, ->(firm_id) { where(firm_id: firm_id) }
	scope :by_user, ->(user_id) { where(user_id: user_id) }

	attr_accessor :user_email, :user_phone, :password, :password_confirmation,
				  :first_name, :last_name

	before_create :check_attributes!


	def starter?
		if self.firm.starter_email == self.user.email || self.firm.starter_phone == self.user.phone_number
			return true
		end
	end

	private

	def check_attributes!
		if password && password_confirmation && first_name && last_name
			a = User.new(
				email: user_email, phone_number: user_phone,
				password: password, password_confirmation: password_confirmation,
				first_name: first_name, last_name: last_name
				)
			a.save!
			self.user_id = a.id
		else
			if user_email || user_phone
				b =  User.find_by_email_and_phone_number(user_email, user_phone)
				self.user_id = b.id
			end
		end
	end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
	before_action :set_firm
  before_action :set_membership, only: [:edit, :update, :destroy]

  def index
    @memberships = @firm.memberships
  end

  def new
    @membership = Membership.new
  end

  def edit
  end

  def create
    @membership = Membership.new(membership_params)

      if @membership.save
        redirect_to firm_memberships_path(@firm)
        flash[:notice] = 'Pengguna berhasil ditambah ke dalam tim'
      else
        render :new
      end
  end

  def update
    if @membership.update(membership_params)
      redirect_to firm_memberships_path(@firm)
      flash[:notice] = 'Anggota tim berhasil dikoreksi'
    else
      render :edit 
    end
  end

  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to firm_memberships_path(@firm), notice: 'Hak anggota tim berhasil dihapus' }
      format.json { head :no_content }
    end
  end



  private

  def set_membership
    @membership = @firm.memberships.find(params[:id])
  end

  def membership_params
    params.require(:membership).permit(
      :role, :status, :user_email, :user_phone, :user_id, :firm_id,
      :password, :password_confirmation, :first_name, :last_name
    )
  end

end

app/helpers/memberships_helper.rb
module MembershipsHelper

	def member_options
	end

	def role_options
		[ ['Rekan, Sesama Pemilik Usaha', 'Rekan'], 
		  ['Kasir, Penjual, Penjaga Toko', 'Pendapatan'],
		  ['Pengurus pembelian dan pengeluaran', 'Pembayaran']
		]
	end

	def find_membership(firm)
		Membership.find_by_user_id_and_firm_id(current_user.id, firm.id)
	end

end

app/views/memberships/_form.html.erb
<%= bootstrap_form_for([@firm, @membership], layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f|  %>

  <%= render 'shared/error_messages', object: @membership %>

  <div class="container">
    <div class="well row">
    	<% unless defined?(edit) && edit %>
		    <div class="col-xs-12" data-toggle="tooltip" 
		        title="masukkan alamat email milik rekan kerja yang telah terdaftar di situs ini">
		    <%= f.text_field :user_email,  label: "Email Rekan Kerja", required: true %>
		    </div>
		    <div class="col-xs-12" data-toggle="tooltip" 
		        title="masukkan nomor telepon milik rekan kerja yang telah terdaftar di situs ini">
		    <%= f.text_field :user_phone,  label: "Nomor Telepon Rekan Kerja", required: true %>
		    </div>
	    <% end %>
	    <% if defined?(register) && register %>
          <div class="col-xs-12 col-sm-6">
            <%= f.password_field :password, class: "form-control", label: 'Kata Kunci', placeholder: "panjang minimal 8 karakter dapat berisi huruf dan angka", required: true %>
          </div>
          
          <div class="col-xs-12 col-sm-6">
            <%= f.password_field :password_confirmation, class: "form-control", label: 'Konfirmasi Kata Kunci', placeholder: "masukkan kata kunci yang sama untuk memastikan", required: true %>
          </div>
                  
          <div class="col-xs-12 col-sm-6">
            <%= f.text_field :first_name, label: "Nama Depan", class: "form-control", help: "Jika tidak ada nama belakang,", required: true %>
          </div>
          
          <div class="form-group col-lg-6">
            <%= f.text_field :last_name, label: "Nama Belakang", class: "form-control", help: "cukup isi nama depan saja" %>
          </div>      
	    <% end %>

	    <div class="col-xs-12" data-toggle="tooltip" 
	        title="peran akan menentukan sejauh mana akses pembukuan diberikan">
	    <%= f.select :role, role_options, prompt: "Pilih Peran", label: "Peran di Usaha" %>
	    </div>
	</div>
	    
	    <%= f.hidden_field :status, value: "Aktif" %>
	    <%= f.hidden_field :firm_id, value: @firm.id %>
	   
    <div class="actions">
      <%= f.submit "Simpan", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<% title("Koreksi Anggota") %>

<%= render partial: 'form', locals: { edit: true } %>

<%= link_to 'Kembali', firm_memberships_path(@firm) %>

app/views/memberships/index.html.erb
<% title("Laman Tim") %>

<div class="container">
	<h3 class="text-center">Daftar Pengguna Yang Terlibat</h3>

	Tambah Anggota Tim
		<%= link_to "+ Pengguna Yang Terdaftar", new_firm_membership_path(@firm), class: "btn btn-md btn-primary" %> 

		<%= link_to "+ Anggota Yang Belum Mendaftar", new_firm_membership_path(@firm, register: true), class: "btn btn-md btn-info" %> 

 	<hr>
	<div class="row">
	  <div class="col-lg-12">
		<div class="main-box no-header clearfix">
		  <div class="main-box-body clearfix">
			<div class="table-responsive">
			  <table class="table user-list">
				<thead>
				  <tr>
					<th class="text-center"><span>User</span></th>
					<th class="text-center"><span>Bergabung</span></th>
					<th class="text-center"><span>Status</span></th>
					<th class="text-center"><span>Mendaftar</span></th>
					<th></th>
					<th></th>
				  </tr>
				</thead>
				<tbody>

				<% @memberships.each_with_index do |member, index| %>
				<tr>
				  <td>
					<h5 class="turq"><%= member.user.full_name %></h5>
					<span class="user-subhead">#<%= index + 1 %>. <%= member.role %></span>
				  </td>
				  <td class="text-center"><%= member.created_at %></td>
				  <td class="text-center"><%= member.status %></td>
				  <td class="text-center"><%= member.user.created_at %></td>
				  <td style="width: 25%;">
				  <% if find_membership(member.firm).role == 'Pemilik' && member.role != 'Pemilik' %>
					
					  <%= link_to edit_firm_membership_path(member.firm, member), class: "table-link" do %>
						<span class="fa-stack">
						  <i class="fa fa-square fa-stack-2x"></i>
						  <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
						</span>Koreksi Anggota Tim #<%= index + 1 %>
				  	  <% end %>
				  </td>
				  <td style="width: 25%;">
						<%= link_to firm_membership_path(member.firm, member), confirm: 'Kamu yakin?', method: :delete, class: "table-link danger" do %>
							<span class="fa-stack">
								<i class="fa fa-square fa-stack-2x"></i>
								<i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
							</span>Hapus Hak Anggota Tim #<%= index + 1  %>
						<% end %>
					</td>
				  <% end %>
				</tr>
				<% end %>

              	</tbody>
              </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>								

app/views/memberships/new.html.erb
<% title("Tambah Anggota") %>

<% if params[:register] %>
	<%= render partial: 'form', locals: { register: true } %>
<% else %>
	<%= render 'form' %>
<% end %>

<%= link_to 'Kembali', firm_memberships_path(@firm) %>