config/routes.rb
Accounting::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "pages#landing"
  get "home", to: "pages#home", as: "home", as: :user_root
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"

  resources :subscribers, only: :create
  devise_for :users
  resources :subscriptions do
    resources :payments
  end

  resources :firms do
    collection do
      post 'switch'
    end
    resources :memberships
    resources :fiscal_years, only: [:new, :create]
    resources :cash_flows, only: [:show]
    resources :balance_sheets, only: [:show]
    resources :income_statements, only: [:show]
    resources :spendings
    resources :payable_payments
    resources :receivable_payments
    resources :assets do
      collection do
        post 'refresh'
      end
    end
    resources :expenses
    resources :revenues
    resources :other_revenues
    resources :discards
    resources :funds
    resources :loans
    resources :expendables
    resources :merchandises
    resources :works
    resources :materials
    resources :products
    resources :assemblies
  end

  resources :assemblies do
    resources :processings, only: [:index]
  end

  resources :fiscal_years do
    collection do
      post 'closing'
    end
    resources :cash_flows, only: [:show]
    resources :balance_sheets, only: [:show]
    resources :income_statements, only: [:show]
  end

  namespace :admin do
    root "base#index"
    get "out_email", to: "base#out_email"
    post "send_outbound", to: "base#send_outbound"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
    resources :plans
    resources :messages, only: [:index, :new, :create]
    resources :bookings      
  end

end

app/models/expendable.rb
class Expendable < ActiveRecord::Base
  belongs_to :firm, foreign_key: 'firm_id'
  has_many   :discards, as: :discardable
  validates_associated :firm, on: :create
  validates :cost, presence: true, numericality: true
  validates :quantity, presence: true, numericality: true
  validates :measurement, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }  
  
  scope :by_firm, ->(firm_id) { where(:firm_id => firm_id) }
  scope :prepaids, -> { where(item_type: 'Prepaids') }
  scope :supplies, -> { where(item_type: 'Supplies') }
  scope :by_name, ->(name) { where(item_name: name) }  
  scope :available, -> { where(perished: false) }

  after_touch :update_item#, :if => :available
  after_save :touch_reports  

  def code
    name = self.item_name
    date = date_purchased
    return "#{name}, dibeli pada tgl #{date}"
  end

  def cost_per_quantity
    (self.cost / self.quantity).round
  end

  def date_purchased
	  Spending.find_by(firm_id: firm_id, item_name: item_name).date_of_spending
  end

  def year_purchased
	 date_purchased.strftime("%Y")
  end

  def related_spendings
    Spending.by_firm(firm_id).expendables.by_name(item_name)
  end

  def find_report(book)
    book.find_by_firm_id_and_year(firm_id, year_purchased)
  end

  def quantity_remaining
    self.quantity - self.quantity_used
  end

  def cost_remaining
    self.cost - self.cost_used
  end

  private

  def update_item
    update(quantity_used: check_quantity_used, perished: check_status, 
           cost_used: calculate_expense, quantity: check_quantity_bought,
           cost: check_cost_bought)
  end

  def check_status
    check_quantity_used
    if quantity_used == self.quantity
      return true
    else
      return false
    end
  end

  def check_quantity_used
    arr = Discard.by_firm(firm_id).by_item(id)
    quantity_used = arr.map{ |discard| discard.quantity }.compact.sum
    return quantity_used
  end

  def calculate_expense
    arr = Discard.by_firm(firm_id).by_item(id)
    # expensed = arr.map{ |discard| discard.quantity * discard.discardable.cost_per_quantity }.compact.sum
    expensed = arr.map{ |discard| discard.item_value }.compact.sum
    return expensed    
  end

  def check_quantity_bought
    arr = Spending.by_firm(self.firm_id).expendables.by_name(item_name)
    quantity_bought = arr.map{ |spe| spe.quantity }.compact.sum
    return quantity_bought
  end

  def check_cost_bought
    arr = Spending.by_firm(self.firm_id).expendables.by_name(item_name)
    cost_bought = arr.map{ |spe| spe.total_spent }.compact.sum
    return cost_bought
  end

  def touch_reports
    find_report(IncomeStatement).touch
  end

end

app/controllers/expendables_controller.rb
class ExpendablesController < ApplicationController
  before_action :set_firm
  # before_action :require_admin, only: :destroy

  def index
  	@expendables = @firm.expendables.all
  	@item_groups = @expendables.group_by { |item| item.item_name }
  	# @supplies = @firm.expendables.supplies.all
  	# @prepaids = @firm.expendables.prepaids.all
  end

  # def sold
  # end

end

app/helpers/expendables_helper.rb
module ExpendablesHelper

	def perish_status(item)
		if item.perished == true
			content_tag(:h5, 'Habis', class: 'strong coral')
		else
			content_tag(:h5, 'Tersedia', class: 'strong turq')
		end
	end

end

app/views/expendables/index.html.erb
<% title("Daftar Aset Lancar Diperoleh") %>
<h1 class="text-center">Daftar Perlengkapan dan Aset Prabayar</h1> 
<hr></hr>

<% @item_groups.each_with_index do |(name, items), index| %>
<div class="container" id="<%= index %>">
  <div class="row user-menu-container square">

    <div class="col-md-7 user-details">

      <div class="row">
        <div class="col-md-6 no-pad coralbg white">
          <div class="user-pad">
            <h2><%= name %></h2>
            <p> [ <%= items.first.account_type %> ] </p>
            <h3 class="white">
              <i class="fa fa-check-circle-o"></i> 
                <%= items.last.spending.date_of_spending %>
            </h3>
            <h5 class="white">
              <i class="fa fa-folder"></i> 
                <%= items.count %> Catatan transaksi pengeluaran
            </h5><br>
          </div>
        </div>

        <div class="col-md-6 no-pad">
          <div class="col-md-12 no-pad text-center">
              <h3>NILAI PEMBAYARAN</h3>
              <h4 class="value"><%= accumulator(items, 'value', 'money') %></h4><br>
              <h3>TOTAL PEMBAYARAN</h3>
              <h4 class="quantity">
                <%= accumulator(items, 'unit', 'decimal') %>
                <%= items.first.measurement %>
              </h4>
          </div>          
          <h5></h5>
        </div>
      </div>
      <br>
      <div class="row overview">
        <div class="col-md-6 user-pad text-center">
          <h3>TOTAL PEMAKAIAN</h3>
          <h4 class='acc_depr'>
            <%= accumulator(items, 'value_expensed', 'money') %>
          </h4>
        </div>
        <div class="col-md-6 user-pad text-center">
          <h3>NILAI SAAT INI</h3>
          <h4>
            <%= unit_remaining(items, 'value', 'value_expensed', 'money') %> 
          </h4>
        </div>
      </div>
    </div>

    <div class="col-md-1 user-menu-btns">
        <div class="btn-group-vertical square" id="responsive">
            <a href="#tab_<%= index %>_1" class="btn btn-block btn-default active action" data-toggle="tab">
              <i class="fa fa-file-o fa-3x"></i>
            </a>
            <a href="#tab_<%= index %>_2" class="btn btn-default" data-toggle="tab">NILAI
            </a>
            <a href="#tab_<%= index %>_3" class="btn btn-default" data-toggle="tab">OPSI
            </a>            
        </div>
    </div>

    <div class="col-md-4 user-menu user-pad">

      <div class="user-menu-content active" id="tab_<%= index %>_1">
        <h3 class="text-center">Riwayat Pembayaran</h3>
        <ul class="user-menu-list">

          <% items.each do |item| %>
          <li class="row">
            <div class="col-sm-12" style="padding-left: 5px;">
              <small><i class="fa fa-clock-o"></i> 
                <%= item.date_purchased %> | beli <%= (item.unit) %> <%= (item.measurement) %> | <%= has_payable?(item) %>
              </small>
            </div>
            <div class="col-sm-12">
              <h5 class="coral">
                <%= idr_money(item.value) %> 
                (<%= show_value_per_unit(item) %>)
              </h5>
            </div>
            <div class="col-sm-12">
              <%= link_to "Koreksi", edit_firm_spending_path(@firm, item.spending, type: 'Expendable') %>
            </div>
          </li>
          <% end %>

        </ul>
      </div>

        <div class="user-menu-content" id="tab_<%= index %>_2">
          <h3 class="text-center">Nilai Aset</h3>
          <ul class="user-menu-list">

            <% items.each do |item| %>
            <li class="row">
              <div class="col-sm-12">
                <small><i class="fa fa-clock-o"></i> 
                  Dibeli: <%= item.date_purchased %>, <%= show_value_per_unit(item) %>
                </small>
              </div>
              <div class="col-sm-12 coral">
                  <h5><%= idr_money(item.value_expensed) %> telah dipakai</h5>
              </div>
              <div class="col-sm-12">
                <%= perish_status(item) %>
              </div>
            </li>
            <% end %>

          </ul>
        </div>

        <div class="user-menu-content" id="tab_<%= index %>_3">
          <h3 class="text-center">Pilihan Tindakan</h3>
          <ul class="user-menu-list">
            <li>
              <%= link_to new_firm_discard_path(@firm, type: items.last.account_type, name: name), class: "btn btn-labeled btn-lg btn-warning", title: 'Catat persediaan yang telah digunakan dalam operasi usaha', :rel => 'tooltip', "data-placement" => "top" do %>
                <span class="btn-label"><i class="fa fa-tachometer"></i></span>Catat Pemakaian
              <% end %>
              <%= link_to new_firm_spending_path(@firm, type: 'Expendable', sub: items.first.account_type, name: name, measure: items.first.measurement), class: "btn btn-labeled btn-lg btn-warning" do %>
                <span class="btn-label"><i class="fa fa-shopping-cart"></i></span>Catat Penambahan
              <% end %>  
            </li>
          </ul>
        </div>        
    </div>


  </div>
</div>
<% end %>