config/routes.rb
Accounting::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "pages#landing"
  get "home", to: "pages#home", as: "home", as: :user_root
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"

  resources :subscribers, only: :create
  devise_for :users
  resources :subscriptions do
    resources :payments
  end

  resources :firms do
    collection do
      post 'switch'
    end
    resources :memberships
    resources :fiscal_years, only: [:new, :create]
    resources :cash_flows, only: [:show]
    resources :balance_sheets, only: [:show]
    resources :income_statements, only: [:show]
    resources :spendings
    resources :payable_payments
    resources :receivable_payments
    resources :assets do
      collection do
        post 'refresh'
      end
    end
    resources :expenses
    resources :revenues
    resources :other_revenues
    resources :discards
    resources :funds
    resources :loans
    resources :expendables
    resources :merchandises
    resources :works
    resources :materials
    resources :products
    resources :assemblies
  end

  resources :assemblies do
    resources :processings, only: [:index]
  end

  resources :fiscal_years do
    collection do
      post 'closing'
    end
    resources :cash_flows, only: [:show]
    resources :balance_sheets, only: [:show]
    resources :income_statements, only: [:show]
  end

  namespace :admin do
    root "base#index"
    get "out_email", to: "base#out_email"
    post "send_outbound", to: "base#send_outbound"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
    resources :plans
    resources :messages, only: [:index, :new, :create]
    resources :bookings      
  end

end

app/views/shared/_close_prompt.html.erb
   <%= link_to "Tutup Buku", closing_fiscal_years_path(fiscal_year_id: @firm.fiscal_years.current.first), method: :post  %><br>

app/views/shared/_closing_form.html.erb
<%= bootstrap_form_for @form do |f|   %>

  <%= f.text_field :balance_year, value: @next_year %>
  <%= f.text_field :firm_balance, value: @firm.id %>

  <%= f.text_field :statement_year, value: @next_year %>
  <%= f.text_field :firm_statement, value: @firm.id %>
  
  <%= f.text_field :flow_year, value: @next_year %>
  <%= f.text_field :firm_flow, value: @firm.id %>

  <%= f.submit "Simpan", class: "btn btn-primary" %>
<% end %>

app/views/shared/_empty_prompt.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2 col-lg-6 col-lg-offset-3">
    <div class="box">
      <div class="box-icon">
          <span class="fa fa-4x fa-thumbs-o-up"></span>
      </div>

      <div class="info">
      <% if params[:controller] == 'spendings' %>
      
        <% if params[:installment] %>
          <h4 class="text-center">Tidak Ada Hutang, Hore! </h4>
          <p>Untuk melihat riwayat pengeluaran secara lengkap,
          klik tombol di bawah ini atau kembali ke Home page</p>
          <%= link_to "Kembali ke Home", user_root_path, class: "btn btn-success" %>
          <%= link_to "Cek riwayat pengeluaran", firm_revenues_path(@firm), class: "btn btn-primary" %>
        <% else %>
          <h4 class="text-center">Belum ada catatan pengeluaran </h4>
          <p>Untuk mencatat pengeluaran, pilih salah satu tombol di bawah sesuai dengan kelompok pengeluaran.</p>
          <%= link_to "Kembali ke Home", user_root_path, class: "btn btn-success" %>
          <% if firm.type == 'Jual-Beli'  %>
            <div class="btn-group btn-group-justified has-tooltip" data-toggle="tooltip" title="<%= spend_merch_tip %>">
              <%= link_to 'Tambah Stok Produk', new_firm_spending_path(firm, type: "Merchandise"), class: "btn btn-default"  %>
            </div>
          <% elsif firm.type == 'Manufaktur'  %>
            <div class="btn-group btn-group-justified has-tooltip" data-toggle="tooltip" title="<%= spend_material_tip %>">
              <%= link_to 'Catat Pembelian Bahan Baku', new_firm_spending_path(firm, type: "Material"), class: "btn btn-default"  %>
            </div>          
          <% end %>

          <div class="btn-group btn-group-justified has-tooltip" data-toggle="tooltip" title="<%= spend_expendable_tip %>">
            <%= link_to 'Catat Pembelian Aset Lancar', new_firm_spending_path(firm, type: "Expendable"), class: "btn btn-default"  %>
          </div>

          <div class="btn-group btn-group-justified has-tooltip" data-toggle="tooltip" title="<%= spend_fixed_tip %>">
            <%= link_to 'Catat Pembelian Aset Tetap', new_firm_spending_path(firm, type: "Asset"), class: "btn btn-default"  %>
          </div>

          <div class="btn-group btn-group-justified has-tooltip" data-toggle="tooltip" title="<%= spend_expense_tip %>">
            <%= link_to 'Catat Pengeluaran', new_firm_spending_path(firm, type: "Expense"), class: "btn btn-default"  %>
          </div>

          <div class="btn-group btn-group-justified has-tooltip" data-toggle="tooltip" title="<%= spend_payable_tip %>">
            <%= link_to 'Catat Pembayaran Hutang Usaha', new_firm_payable_payment_path(firm, type: "Spending"), class: "btn btn-default" %>
          </div>
        <% end %>

      <% elsif params[:controller] == 'revenues' %>
        <% if params[:installment] %>
          <h4 class="text-center">Tidak Ada Piutang, Hore! </h4>
          <p>Untuk melihat riwayat pendapatan secara lengkap,
          klik tombol di bawah ini atau kembali ke Home page</p>
          <%= link_to "Kembali ke Home", user_root_path, class: "btn btn-success" %>
          <%= link_to "Cek riwayat pendapatan", firm_revenues_path(@firm), class: "btn btn-primary" %>
        <% else %>
          <h4 class="text-center">Belum ada catatan pendapatan</h4>
          <p>Untuk mencatat pengeluaran, pilih salah satu tombol di bawah sesuai dengan kelompok pendapatan.</p>

          <div class="col-md-12 text-center">
            <% if firm.type == 'Manufaktur' %>
              <span class="has-tooltip" data-toggle="tooltip" title="<%= rev_product_tip %>">
                <%= link_to "Catat Penjualan", new_firm_revenue_path(firm, type: 'Product'), class: "btn btn-xs btn-primary" %>
              </span>
            <% elsif firm.type == 'Jasa' %>
              <span class="has-tooltip" data-toggle="tooltip" title="<%= rev_service_tip %>">
                <%= link_to "Catat Pendapatan Operasi", new_firm_revenue_path(firm, type: 'Service'), class: "btn btn-primary" %>
              </span>                
            <% else %>
              <span class="has-tooltip" data-toggle="tooltip" title="<%= rev_merch_tip %>">
                <%= link_to "Catat Penjualan", new_firm_revenue_path(firm, type: 'Merchandise'), class: "btn btn-primary" %>
              </span>
            <% end %>            
          </div>

          <div class="col-md-12">
            <span class="has-tooltip" data-toggle="tooltip" title="<%= rev_asset_tip %>">
              <%= link_to 'Catat Penjualan Aset', new_firm_revenue_path(firm, type: 'Asset'), class: "btn btn-primary" %>
            </span>            
          </div>
          <div class="col-md-12">
            <span class="has-tooltip" data-toggle="tooltip" title="<%= rev_receivable_tip %>">
               <%= link_to 'Catat Pendapatan Piutang',new_firm_receivable_payment_path(firm), class: "btn btn-primary" %>
            </span>            
          </div>
          <div class="col-md-12">
            <span class="has-tooltip" data-toggle="tooltip" title="<%= rev_other_tip %>">
              <%= link_to 'Catat Pendapatan Lain', new_firm_other_revenue_path(firm), class: "btn btn-primary" %>
            </span>            
          </div>
        <% end %>
      <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this spending from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  

app/views/shared/_firm_filter.html.erb
  <%= form_tag('', method: "get", id: "firm_switch") do %>
    <%= select_tag :firm, options_for_select(@firm_options), {prompt: "Pilih Usaha" }  %>
    <%= submit_tag 'Ganti', name: nil, class: "btn btn-success btn-xs" %>
  <% end %>

app/views/shared/_info_panel.html.erb
        <div class="col-md-6 col-sm-6">
          <div class="servive-block servive-block-light-green">
            <i class="fa fa-money fa-2x"></i>
            <p>Kas dan Setaranya</p>
            <p><%= number_to_currency(firm.current_balance_sheet.cash, unit: "Rp", delimiter: ".", precision: 0) %></p>
          </div>
        </div>
        <div class="col-md-6 col-sm-6">
          <div class="servive-block servive-block-dark-blue">
            <i class="fa fa-building-o fa-2x"></i>
            <p class="heading-md">Total Aset</p>
            <p><%= number_to_currency(firm.current_balance_sheet.inventories, unit: "Rp", delimiter: ".", precision: 0) %></p>
          </div>
        </div>

app/views/shared/_plans_table.html.erb
  <div class="row content">
		<div class="col-lg-10 col-lg-offset-1">
					
			<div class="col-sm-6 text-center">
				<div class="plan">
					<p class="icon gold">
						<i class="fa fa-desktop fa-fw"></i>
					</p>
					<h2 class="gold-text">Promo!</h2>
					<p class="gold-text price">Rp 100.000 <br>
					per bulan</p>

					<p>30 Hari Coba Gratis</p>
					<p>Tidak Ada Batas Transaksi</p>
					<p>Semua Fitur Pembukuan</p>
					<a class="btn btn-pricing" href="<%=  new_user_registration_path %>">Daftar Sekarang</a>
				</div>
				<br>
				<br>
				<br>
			</div>

			<div class="col-sm-1">
			</div>

			<div class="col-sm-4">
				<hr class="intro-divider">
				<h2>Masa Promosi!</h2>
				<p class="lead justify-text">Daftar sekarang dan coba gratis selama 30 hari! Semua fitur pembukuan telah bisa diakses sekarang.</p>
			</div>
			<div class="col-sm-1">
			</div>			
		</div>
	</div>

app/views/shared/_subscribe_panel.html.erb
    <div class="panel panel-success">
      <div class="panel-body">
        <strong>Masih ragu untuk mendaftar?</strong>
        <p>
           Jika masih dalam pertimbangan, silahkan masukkan email kamu ke kotak di bawah ini agar kami bisa mengabari kamu perkembangan aplikasi ini ke depannya.
        </p>
        <%= form_for(@subscriber) do |f| %>
          <div class="form-group">
            <div class="input-group" id="subscribe">
              <span class="input-group-addon">
                <i class="fa fa-envelope" aria-hidden="true"></i>
              </span>
                <%= f.text_field :email %>
            </div>
            <br>
            <p>
              <%= f.submit "Simpan", class: "btn btn-md btn-primary", id: "subscribe-button" %>
            </p>
            
          </div>
        <% end %>
      </div>
    </div>

app/views/shared/_trial_expiration_panel.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2 col-lg-6 col-lg-offset-3">
    <div class="box">
      <div class="box-icon">
          <span class="fa fa-4x fa-exclamation"></span>
      </div>
      <div class="info">
        <% if @firm.has_no_subscription? %>
          <h4 class="text-center">Masa Uji Coba Telah Habis</h4>
          <p>Maaf, masa uji coba untuk akun <%= @firm.name %> telah berakhir. Untuk melanjutkan penggunaan, silahkan klik tombol di bawah untuk berlangganan</p>
          <%= link_to "Jadi Pelanggan Tetap", new_subscription_path(name: @firm.name, number: @firm.id), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>